### ISSUE TITLE
Thunderbolt - "Disconnect GPU" issue (minor)

### ISSUE THREAD

**Issue by velaar** [benbender/x1c6-hackintosh#2]
When I use the "Disconnect GPU button" it turns off both the builtin and the external (eGPU) connected screen. 
I wonder if there is a good way to diagnose this. 

Once I physically unplug the GPU, the builtin screen comes on and works as expected.

**Comment by benbender** [comment]
@velar please provide logs for when this happens (`log show --last 1m > I-disconnected-my-eGPU-and-unplugged-my-cable.log`) and a dump by https://github.com/vulgo/IORegistryExplorer after you disconnected the cable (so that the removed devices are visible in red in the dump).

**Comment by velaar** [comment]
Closed. Was unable to replicate the issue on the current repo. No idea what happened.
