### ISSUE TITLE
ARPT SSDT on T460

### ISSUE THREAD

**Issue by Charlyo** [benbender/x1c6-hackintosh#3]
Dear @benbender! 

Wanted to try the ARPT script in my T460 with an original BCM 4360cs2 installed. However my wifi card pcie slot ACPI naming doesn't match. 

![Screenshot 2020-11-01 at 23 12 12](https://user-images.githubusercontent.com/7512047/97816785-edc9d900-1c97-11eb-9242-fc5aeedb3e13.png)

Two questions come into mind:
- Should I change RP09 to the actual EXP3?
- Is there any other SSDT needed for this one to actually correctly work.

Thank you very much.

**Comment by benbender** [comment]
Technically yes. It should be `\_SB.PCI0.EXP3`. But from my experience I wouldn't recommend the effort. At the moment the benefit seems negligible - if any.

**Comment by Charlyo** [comment]
Noted! Then I'll wait until further results are achieved.

PS. I do have a family member 2014 15" MacbookPro11,3. If you need any data from it (ACPI / Dumps) just let me know

**Comment by benbender** [comment]
@Charlyo thanks for the offer but many models can be found here: https://github.com/khronokernel/DarwinDumped/tree/master/MacBookPro 

Without this repo much of what I've done wouldn't have been possible :)

(If you have access to a model which is missing or incomplete it would be glorious to add/fix them though!)

**Comment by Charlyo** [comment]
Fortunately they got it already covered :)
