### ISSUE TITLE
Performance bad with DYTC?

### ISSUE THREAD

**Issue by buyddy** [benbender/x1c6-hackintosh#4]
It seems that when DYTC is enabled, my i7-8650U is power limited to about 15W. When running Cinebench 20. The score is 1220 under Balanced mode and 1250 under Performance. The power limit set by VoltageShift is not working anymore. Before I use VoltageShift to set power limit to 25W with AC connected and my benchmark was 1574. A very big performance drop. Can others also confirms that?

**Comment by EETagent** [comment]
Yeah, I am getting similar score with DYTC on maximum performance. Previously 1540-1500. I did not have much time recently though to test if it's exactly DYTC to blame.

**Comment by buyddy** [comment]
@benbender I assume we can just change SSDT-INIT and go back to DPTF, and only thermal control will be impacted but not other YogaSMC functions?

**Comment by benbender** [comment]
Sure. But I don't think it will solve your problem. DPTF needs userspace-drivers which aren't available on OSX. Additionally Voltageshift should use direct writes to the MSR-Registers of the CPU, don't see how that correlates. I would suggest to narrow the reason down.

**Comment by buyddy** [comment]
> Sure. But I don't think it will solve your problem. DPTF needs userspace-drivers which aren't available on OSX. Additionally Voltageshift should use direct writes to the MSR-Registers of the CPU, don't see how that correlates. I would suggest to narrow the reason down.

Can we enable both DPTF and DYTC or only one? The MSR-Register seems to be correctly written but somehow a thermal throttling (looks more like power limit) kicked in.

**Comment by buyddy** [comment]
@EETagent  This is confirmed, revert back to DPTF I can get 25W. CPU core can reach 90 degree Celsius now. I think either DYTC is overly conservative. Or I am not able to unlock the "performance" level and got stuck on the balanced level.  
@benbender If you run a CPU test in Intel Power Gadget, what is the constant power limit are you seeing with DYTC under "Performance" Level?

**Comment by benbender** [comment]
@buyddy I can reach 25W-PL2-boost. But it's not meant to be sustained for a longer period of time. It's PL2-boost and according to the specs, the limit falls down to 15W after the boost-time-window. With slight undervolting and no additional steps. Don't see a problem here tbh. But at the same time, I'm also not in the need of the last few percent performance the system might have.

**Comment by buyddy** [comment]
@benbender I think the DYTC has a limit on either power or temperature. The fan almost never spin in this case. Temp stay down around 70C. Without it I can have L1 to be 25W and core temp reach at most 90C with 86C being most of the time. I think I would rather prefer to use voltage control to do the job.

**Comment by benbender** [comment]
@buyddy Whatever fits your needs :) My understanding is that DYTC doesn't work correctly without os-drivers - which do not exist for OSX afaik. DYTC is, afaik, only a wrapper around DPTF which replaces parts of the OS-drivers in ACPI to make it OS-independant. But as I said, I don't have any load I run regularly that would make me notice either of those.
