### ISSUE TITLE
BigSur power consumption 

### ISSUE THREAD

**Issue by velaar** [benbender/x1c6-hackintosh#5]
**20B5022a**

Over 13W constant drain. Seems to be coming from the CPU. Were there any significant changes to CPUFriend // performance vectors? 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/4062230/98469222-3e679780-21ac-11eb-89dc-8e24a293996a.png">

Can't convince the system to stay low. Tried CPUFriendFriend but the total PKG doesn't seem to go under r@t

<img width="388" alt="image" src="https://user-images.githubusercontent.com/4062230/98469013-26dbdf00-21ab-11eb-89d3-50b9a539d412.png">

Nothing too suspicious in the Activity monitor:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/4062230/98469186-1a0bbb00-21ac-11eb-914f-6ee984cc4537.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/4062230/98469195-2a239a80-21ac-11eb-94cb-62a7138c92ff.png">

**Comment by buyddy** [comment]
I found using yogasmc drain more power too.

**Comment by benbender** [comment]
@velaar I "only" see the 10W on 1 Screenshot and not on the others. Could you elaborate on the problem? Besides that, CPUFriendProvider is simply created with this: https://github.com/fewtarius/CPUFriendFriend (slightly advanced version not yet in mainline).

@buyddy that's definitely a false claim.

**Comment by buyddy** [comment]
> @velaar I "only" see the 10W on 1 Screenshot and not on the others. Could you elaborate on the problem? Besides that, CPUFriendProvider is simply created with this: https://github.com/fewtarius/CPUFriendFriend (slightly advanced version not yet in mainline).
> 
> @buyddy that's definitely a false claim.

Could be the way battery was reporting. But I do notice the battery indicator behaved differently. Now I am testing 14,1 as you suggested with Yogasmc.

**Comment by benbender** [comment]
I'm ~ 0.7-0.8W idle on two machines with YogaSMC and I'm using it for quite a while now so I'm pretty sure it doesn't brick your power usage.

**Comment by buyddy** [comment]
> I'm ~ 0.7-0.8W idle on two machines with YogaSMC and I'm using it for quite a while now so I'm pretty sure it doesn't brick your power usage.

I could never achieve that idle power. I have a second ssd and my wifi card is 1820a so no ASPM. Quite annoying.

**Comment by velaar** [comment]
Ok. Continuing my research. Thanks to @benbender for suggesting powermetrics to track power consumption. 

The core finding is this: 

```
System Average frequency as fraction of nominal: 84.67% (1777.97 Mhz)
Package 0 C-state residency: 28.52% (C2: 7.99% C3: 20.53% C6: 0.00% C7: 0.00% C8: 0.00% C9: 0.00% C10: 0.00% )

```

In other words CPU package does not enter C7 (while it does on Windows and Linux - tested). 
Internet suggested many things, but this is what was tested on my side (to no result)

* Disabling audio/AppleALC
* Disabling intel ethernet
* Disabling TB

Something else keeps the power state of the package high. While the cores do go all the way to C7
>Core 0 C-state residency: 58.48% (C3: 0.93% C6: 0.00% C7: 57.55% )

iGPU also goes quite low. 
>GPU 0 average active frequency as fraction of nominal (300.00Mhz): 100.00% (300.00Mhz)

Also worth noting: 
```
GPU 0 GPU Busy                      : 11.54%
GPU 0 DC6 Residency                 : 0.00%
GPU 0 [PSR] GPU + TCON are Off      : 0.00%
GPU 0 [PSR] Only GPU is On          : 100.00%
GPU 0 [PSR] Only TCON is On         : 0.00%
GPU 0 [PSR] GPU + TCON are On       : 0.00%
GPU 0 [PSR] StateMachine Bypass     : 100.00%
GPU 0 [PSR] StateMachine FIFO       : 0.00%
```

**Comment by benbender** [comment]
@velaar As noted before, I don't have a good advice to give, but I can give the following hints:

- my CPU is going down to C8 on Catalina & BigSur and you are right, that's your problem
- the GPU on the other hand doesn't have complete power-management as we have no way to load apple's specific & signed GuC (Intel GPU fw). So this is "normal" for (most) hackintoshes.

**Comment by benbender** [comment]
I think I found the actual issue and it should be fixed with the latest changes in the TB-code. Closing for now.
