### ISSUE TITLE
Info regarding Lenovo's ACPI

### ISSUE THREAD

**Issue by antoniomcr96** [benbender/x1c6-hackintosh#6]
I apreciate all the work you did to improve the experience with Lenovo Laptops. I’m trying to apply your patches to my Lenovo L390, and I have some questions:

1. does creating a fake `ALS0`, `PWRB`, and `DMAC` device improve somehow the experience or the performance of the machine?

2. i have a `MATH` device in my DSDT ("`PNP0C04`”), do I need to rename it in `MAT0` or it doesnt matter? If I rename it nothing changes in IOReg, so I don't know if it has any effect.

3. I applied your HWAC patch for 16-bit EC access. In my DSDT XWAC is called under _L17:

```
 Method (_L17, 0, NotSerialized)  // _Lxx: Level-Triggered GPE, xx=0x00-0xFF
        {
            Local0 = \_SB.PCI0.LPCB.H_EC.XWAC /* External reference */
```
The problem is that **XWAC isn’t called as a method**. (Originally it was HWAC, but I did a rename of EC.HWAC -> EC.XWAC). It is called as an object, as it was HWAC, and in fact it is defined as an external object in the begging of my DSDT:
`    External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)
`
(Unfortunately the rename affects also this sequence)

So I think that the method that you created with the SSDT is never called in my ACPI, but I might be wrong. Maybe it could work if I define it as an object

4. I have only a battery (BAT0). Can I use your SSDT or do you have a version for systems with only one battery?

5. EDIT: Patched ADP1, now ACPIACAdapter attaches to the device. Thanks!
_In my DSDT it is already defined a device called ADP1, but it doesn’t have a method PRW. Is it useful to add a method PRW like in your SSDT?_

6. I think that your SSDT-INIT could work also without patching OINI -> ZINI. The values could be set without calling OINI method:
```
Scope (\)
    {
        If (OSDW ())
        {
            STAS = One //AWAC
            GPHD = Zero //GPIO

            HPTE = Zero
            WNTF = One
            DPTF = Zero
        }
    }
```
This avoids a rename and, in this case, allows to merge SSDT-AWAC, GPIO (for who needs them) and INIT.
I don't know if it works for `OSYS` because I think this value could be rewritten in `SB.PCI0._INI` method. 

Thanks in advance for ALL your help and greetings for all your work. Have a nice day

**Comment by benbender** [comment]
EDIT: I just had a brief search for the L390 DSDT and couldn't find it, but it seems that it belongs hardware-vise more to the Yoga-lineup of Lenovo. If thats the case especially the EC (embedded controller) might be quite different to the H8S-ECs of the t- and x-series. If that's the case, that may be the cause for the problems with HWAC and potentially also the SSDT-BATX-patches. Please attach your DSDT (export simply via MacIASL) and I'll have a look.


> I apreciate all the work you did to improve the experience with Lenovo Laptops. I’m trying to apply your patches to my Lenovo L390, and I have some questions:
> 
> 1. does creating a fake `ALS0`, `PWRB`, and `DMAC` device improve somehow the experience or the performance of the machine?

The answer is not that clear. No they shouldn't affect performance directly but f.e. the missing ambient light sensor (ALS0) may result in errors which are clearly not helping performance either.

> 2. i have a `MATH` device in my DSDT ("`PNP0C04`”), do I need to rename it in `MAT0` or it doesnt matter? If I rename it nothing changes in IOReg, so I don't know if it has any effect.

Nope. If it shows up in IOReg its fine. Most OSX-drivers dont match by name these days anyways.

> 3. I applied your HWAC patch for 16-bit EC access. In my DSDT XWAC is called under _L17:
> 
> ```
>  Method (_L17, 0, NotSerialized)  // _Lxx: Level-Triggered GPE, xx=0x00-0xFF
>         {
>             Local0 = \_SB.PCI0.LPCB.H_EC.XWAC /* External reference */
> ```
> 
> The problem is that **XWAC isn’t called as a method**. (Originally it was HWAC, but I did a rename of EC.HWAC -> EC.XWAC). It is called as an object, as it was HWAC, and in fact it is defined as an external object in the begging of my DSDT:
> ` External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)`
> (Unfortunately the rename affects also this sequence)
> 
> So I think that the method that you created with the SSDT is never called in my ACPI, but I might be wrong. Maybe it could work if I define it as an object

HWAC should be a FieldUnitObj from EmbeddedControl-OperationRegion. Therefor I'm a bit confused with the ÌntObj`... Replacing a read with an method is support even if it may be slightly out of spec (never checked to be honest). Can't say anymore without seeing your DSDT.

> 1. I have only a battery (BAT0). Can I use your SSDT or do you have a version for systems with only one battery?

BATX works transparently with single- and dual-battery-setups as long as the EC-layout matches.

> 2. EDIT: Patched ADP1, now ACPIACAdapter attaches to the device. Thanks!
>    _In my DSDT it is already defined a device called ADP1, but it doesn’t have a method PRW. Is it useful to add a method PRW like in your SSDT?_

Yes, as you found out by yourself ;)

> 3. I think that your SSDT-INIT could work also without patching OINI -> ZINI. The values could be set without calling OINI method:
> 
> ```
> Scope (\)
>     {
>         If (OSDW ())
>         {
>             STAS = One //AWAC
>             GPHD = Zero //GPIO
> 
>             HPTE = Zero
>             WNTF = One
>             DPTF = Zero
>         }
>     }
> ```
> 
> This avoids a rename and, in this case, allows to merge SSDT-AWAC, GPIO (for who needs them) and INIT.
> I don't know if it works for `OSYS` because I think this value could be rewritten in `SB.PCI0._INI` method.

You exactly found the reason why I do all those stuff in OINI() - because OSYS gets overwritten otherwise. There may also be problems with the EC not ready before. So it should be safer and cleaner.

**Comment by antoniomcr96** [comment]
Thanks for your time (a lot!)
This is my DSDT, unfortunately it is the first project on a L390 so I don't have anything available for a comparison. Converted to txt to upload here on GitHub
[L390 (Yoga) DSDT.txt](https://github.com/benbender/x1c6-hackintosh/files/5539321/L390.Yoga.DSDT.txt)
At the moment there isn't the `H_EC.HWAC` -> `H_EC.XWAK` rename. If I include your HWAC-SSDT
```
DefinitionBlock ("", "SSDT", 2, "tyler", "_HWAC", 0x00001000) {
    External (_SB_.PCI0.LPCB.H_EC, DeviceObj)
    External (_SB_.PCI0.LPCB.H_EC.HWAC, FieldUnitObj)
    External (HWAC, IntObj)
    External (OSDW, MethodObj)

    Scope (\_SB.PCI0.LPCB.H_EC) {
        OperationRegion (ERAM, EmbeddedControl, Zero, 0x0100)
        Field (ERAM, ByteAcc, NoLock, Preserve) {
            Offset (0x36), 
            WAC0,   8, 
            WAC1,   8
        }

        Method (XWAC, 0, NotSerialized) {
            If (OSDW()) {
                Local0 = (WAC1 << 0x08)
                Local0 |= WAC0 /* \_SB_.PCI0.LPCB.H_EC.WAC0 */
                Return (Local0)
            }
            Else {
                Return (HWAC) /* External reference */
            }
        }
    }
}
```
It adds an` External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` on the top on my DSDT, even though XWAC should be a methodObj and not an IntObj. Maybe ACPI works this way and I'm wrong.

Only if you have time let me know if I can inject your BATX SSDT and if your SLEEP SSDT may fit my ACPI table. I'll investigate them in the next days, but maybe you can tell me before if it's not possible.

> Nope. If it shows up in IOReg its fine. Most OSX-drivers dont match by name these days anyways.

Unfortunately it doesn't show in IOReg neither with MATH name neither with MAT0 name. Maybe it is missing some methods.

> You exactly found the reason why I do all those stuff in OINI() - because OSYS gets overwritten otherwise. There may also be problems with the EC not ready before. So it should be safer and cleaner.

Is setting `OSYS` so important? Does it avoid to define useless device or things like this? My IOReg doesn't change

Thanks again

**Comment by benbender** [comment]
> Thanks for your time (a lot!)

You're welcome.

> This is my DSDT, unfortunately it is the first project on a L390 so I don't have anything available for a comparison. Converted to txt to upload here on GitHub
> [L390 (Yoga) DSDT.txt](https://github.com/benbender/x1c6-hackintosh/files/5539321/L390.Yoga.DSDT.txt)

for the future: leave the ending on asl/dsl and just zip it. Much smaller filesize to upload ;)

> At the moment there isn't the `H_EC.HWAC` -> `H_EC.XWAK` rename. If I include your HWAC-SSDT
> It adds an` External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` on the top on my DSDT, even though XWAC should be a methodObj and not an IntObj. Maybe ACPI works this way and I'm wrong.

According to your DSDT, that seems to be correct. The problem is more like the patch in config.plist. Would need the compiled DSDT to compare (export via Hackintools -> Utilities -> "Dump ACPI" on the bottom

> Only if you have time let me know if I can inject your BATX SSDT and if your SLEEP SSDT may fit my ACPI table. I'll investigate them in the next days, but maybe you can tell me before if it's not possible.

BATX won't work for you as your EC has another layout, even if the technique I used is completely adoptable. Its mainly about the offset and the fact that your EC doesn't use bank switching (needs to be removed from BATX - all the HIID-stuff).

Sleep may not work either as your system is another platform with another featureset. 

> Unfortunately it doesn't show in IOReg neither with MATH name neither with MAT0 name. Maybe it is missing some methods.

~I don't see a MATH-device in your DSDT. Leave it like it is.~

Edit:
`````
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If ((PCHS == PCHH))
                {
                    Return (0x1F)
                }
                Else
                {
                    Return (0x00)
                }
            }
`````

Overlooked the device and its simply disabled on your model. (`_STA()` needs to return 0xFF to be enabled.) You can patch it, but i don't think it makes much of a difference.

> Is setting `OSYS` so important? Does it avoid to define useless device or things like this? My IOReg doesn't change

In many cases yes. It tells the ACPI about the OS which is running. Acidanthera generally opts against patching it, but often advanced features or specific hardware is disabled by default if you don't patch it.

**Comment by antoniomcr96** [comment]
> > At the moment there isn't the `H_EC.HWAC` -> `H_EC.XWAK` rename. If I include your HWAC-SSDT
> > It adds an` External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` on the top on my DSDT, even though XWAC should be a methodObj and not an IntObj. Maybe ACPI works this way and I'm wrong.
> 
> According to your DSDT, that seems to be correct. The problem is more like the patch in config.plist. Would need the compiled DSDT to compare (export via Hackintools -> Utilities -> "Dump ACPI" on the bottom

[DSDT.aml.zip](https://github.com/benbender/x1c6-hackintosh/files/5540445/DSDT.aml.zip)
I replace `45434857 41436070` with `45435857 41436070` (4543)HWAC(6070) to (4543)XWAC(6070). I load the ssdt as this comment https://github.com/benbender/x1c6-hackintosh/issues/6#issuecomment-727038295 . 
On the top of my DSDT (opened in MaciASL) it appears an external reference `External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` even though it should be a method. I don't know if it is wrong or not

> Sleep may not work either as your system is another platform with another featureset.

I'll probably give up on battery info, it is out of my reach, but I'll try to implementate SLEEP. I'll investigate the ssdt in the next days because of university exam. Just two questions:
1. https://github.com/benbender/x1c6-hackintosh/blob/e04cbc7196833b706b0cd4765663d0ecda3514bb/EFI/OC/dsl/SSDT-SLEEP.dsl#L142 from this line to line 167: you check the bios settings and set `_S3` and `SS3`. For me `_S3` is already defined as yours and `SS3` is already One.
For me `STY0` doesn't exist, but I think it shouldn't be necessary (it is called only between those lines). So for the first part I should only set `S0ID` to 0, right?

2. https://github.com/benbender/x1c6-hackintosh/blob/e04cbc7196833b706b0cd4765663d0ecda3514bb/EFI/OC/dsl/SSDT-SLEEP.dsl#L285 You set `PMEE` for shutdown for various devices. 
I think that for you `RP09` should be related to Thunderbolt, but I don't have thunderbolt: for me it is the NVMe SSDT. Should I remove that part or do anything to shutdown the NVMe?

https://github.com/benbender/x1c6-hackintosh/blob/e04cbc7196833b706b0cd4765663d0ecda3514bb/EFI/OC/dsl/SSDT-SLEEP.dsl#L307 what is this USBM() method for? I took a look to your SSDT-XHC but I define my USB with USBMap, so I don't have that method. Is it necessary to shutdown? Because it seems complex

Why don't you set PMEE for other PCI devices like HDEF, I2C, CNWV, isn't necessary? 

Thanks as always

**Comment by benbender** [comment]
> 45435857 41436070



> > > At the moment there isn't the `H_EC.HWAC` -> `H_EC.XWAK` rename. If I include your HWAC-SSDT
> > > It adds an` External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` on the top on my DSDT, even though XWAC should be a methodObj and not an IntObj. Maybe ACPI works this way and I'm wrong.
> > 
> > 
> > According to your DSDT, that seems to be correct. The problem is more like the patch in config.plist. Would need the compiled DSDT to compare (export via Hackintools -> Utilities -> "Dump ACPI" on the bottom
> 
> [DSDT.aml.zip](https://github.com/benbender/x1c6-hackintosh/files/5540445/DSDT.aml.zip)
> I replace `45434857 41436070` with `45435857 41436070` (4543)HWAC(6070) to (4543)XWAC(6070). I load the ssdt as this comment [#6 (comment)](https://github.com/benbender/x1c6-hackintosh/issues/6#issuecomment-727038295) .
> On the top of my DSDT (opened in MaciASL) it appears an external reference `External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` even though it should be a method. I don't know if it is wrong or not
> 

Your replace `45435857 41436070` is  `ECXWACp` in ascii. It doesn't match your `H_EC`-device. To find the right match and replace one needs to decompile the actual binary-DSDT with `iasl -l` ("-l                  Create mixed listing file (ASL source and AML) (*.lst)") and find the right spot to replace.

> > Sleep may not work either as your system is another platform with another featureset.
> 
> I'll probably give up on battery info, it is out of my reach, but I'll try to implementate SLEEP. I'll investigate the ssdt in the next days because of university exam. Just two questions:
> 
> 1. https://github.com/benbender/x1c6-hackintosh/blob/e04cbc7196833b706b0cd4765663d0ecda3514bb/EFI/OC/dsl/SSDT-SLEEP.dsl#L142
>     from this line to line 167: you check the bios settings and set `_S3` and `SS3`. For me `_S3` is already defined as yours and `SS3` is already One.

It originates from a specialty for the X1C6 where lenovo added S3 later on by public demand. The X1C6 has a bios option for sleep for "windows" (aka S0) or "linux" (aka S3). This forces S3 for OSX independent of the BIOS-setting. Should be irrelevant for you and can be removed.

>    For me `STY0` doesn't exist, but I think it shouldn't be necessary (it is called only between those lines). So for the first part I should only set `S0ID` to 0, right?

It depends on how your device behaves on S0 in OSX. The thing is that `ACPI-S0` of OSX isn't identical to "modern standby" of windows. Windows uses a standard added in ACPI 6 where OSX uses a custom implementation in OSX-drivers and their custom ACPI based on the `SLTP`-var (`XLTP` in my patches). So afaik its hard to predict how a device behaves with S0 enabled. S3 is the save bet as it's an actual standard in both worlds.

> 2. https://github.com/benbender/x1c6-hackintosh/blob/e04cbc7196833b706b0cd4765663d0ecda3514bb/EFI/OC/dsl/SSDT-SLEEP.dsl#L285
>     You set `PMEE` for shutdown for various devices.
>    I think that for you `RP09` should be related to Thunderbolt, but I don't have thunderbolt: for me it is the NVMe SSDT. Should I remove that part or do anything to shutdown the NVMe?

It depends. If your ACPI uses PME, which is a ACPI/PCI standard mechanism enabling devices to wake itself... Its the common reason where user-shutdown leads to a reboot on hackintoshs. Often this signal is set somewhere in the original ACPI on sleep and never gets cleared as apple doesn't seem to use this mechanism (they use wakeups via RTC). Therefor its relatively save to force it to Zero to fix reboot-issues on shutdown. If you don't have reboot issues, you can mostly remove it / leave it alone.

> https://github.com/benbender/x1c6-hackintosh/blob/e04cbc7196833b706b0cd4765663d0ecda3514bb/EFI/OC/dsl/SSDT-SLEEP.dsl#L307
> 
> what is this USBM() method for? I took a look to your SSDT-XHC but I define my USB with USBMap, so I don't have that method. Is it necessary to shutdown? Because it seems complex

It was an experiment. Don't know for sure what it does exactly. It originates from apples XHC-implementation on macbookpro14,1.

> Why don't you set PMEE for other PCI devices like HDEF, I2C, CNWV, isn't necessary?

They don't use it in the X1C6-ACPI. Therefor no need to.

> 
> Thanks as always

**Comment by antoniomcr96** [comment]
> > > According to your DSDT, that seems to be correct. The problem is more like the patch in config.plist. Would need the compiled DSDT to compare (export via Hackintools -> Utilities -> "Dump ACPI" on the bottom
> > 
> > 
> > [DSDT.aml.zip](https://github.com/benbender/x1c6-hackintosh/files/5540445/DSDT.aml.zip)
> > I replace `45434857 41436070` with `45435857 41436070` (4543)HWAC(6070) to (4543)XWAC(6070). I load the ssdt as this comment [#6 (comment)](https://github.com/benbender/x1c6-hackintosh/issues/6#issuecomment-727038295) .
> > On the top of my DSDT (opened in MaciASL) it appears an external reference `External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` even though it should be a method. I don't know if it is wrong or not
> 
> Your replace `45435857 41436070` is `ECXWACp` in ascii. It doesn't match your `H_EC`-device. To find the right match and replace one needs to decompile the actual binary-DSDT with `iasl -l` ("-l Create mixed listing file (ASL source and AML) (*.lst)") and find the right spot to replace.

![image](https://user-images.githubusercontent.com/63928525/99193378-d5b68700-2778-11eb-9c91-08f7122a4415.png)
I replace this with XWAC, and the replace works. Then I add your HWAC SSDT.
 
[System DSDT.zip](https://github.com/benbender/x1c6-hackintosh/files/5542892/System.DSDT.zip)
This is my DSDT after the HWAC-SSDT and the rename. HWAC is correctly renamed in XWAC, but on the top of the DSDT I have a `External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)` that instead should be a MethodObj, I think!

Have a nice day!

**Comment by benbender** [comment]
@antoniomcr96 please extract your DSDT via Hackintool and upload the original DSDT.**aml** (aka the binary!) - ideally without the XWAC-patch

**Comment by antoniomcr96** [comment]
> [DSDT.aml.zip](https://github.com/benbender/x1c6-hackintosh/files/5540445/DSDT.aml.zip)

This is my original DSDT without patches in AML. I attached it in https://github.com/benbender/x1c6-hackintosh/issues/6#issuecomment-727182409 . Did I do anything wrong?

**Comment by benbender** [comment]
Ah, sorry, my fault. I already had a DSDT.aml in my downloads-folder and didn't noticed. I thought you uploaded the wrong file. Will have a look.

**Comment by benbender** [comment]
Try:

`48 5F 45 43 48 57 41 43` -> `48 5F 45 43 58 57 41 43`

**Comment by antoniomcr96** [comment]
Thanks, replace works but the problem is the same. On the top of my DSDT I have a :
`    External (_SB_.PCI0.LPCB.H_EC.XWAC, IntObj)
` whereas it should be a method, I think.
https://acpica.org/sites/acpica/files/aslcompiler_10.pdf Looking in this document, if iasl decompiles and doesn't find an ACPI name inside the document it automatically creates an External reference of that name on the top of the table (section 4.2.2)
In my DSDT, but I think also in the DSDT of X1C6, XWAC is called as an IntObject and not as a method.

[DSDT.zip](https://github.com/benbender/x1c6-hackintosh/files/5543344/DSDT.zip)
This is my DSDT, HWAC -> XWAC correctly replaced:
```
 Scope (\_GPE)
    {
        Method (_L17, 0, NotSerialized)  // _Lxx: Level-Triggered GPE, xx=0x00-0xFF
        {
            Local0 = \_SB.PCI0.LPCB.H_EC.XWAC /* External reference */
```
As you can see in Method _L17 there is a call to XWAC, but not as a method. But XWAC exists only as a Method for us. I also gave a look to [X1C6 DSDT](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/ACPI/Disassembled%20ACPI/BIOS-v1.45/DSDT.dsl) and the situation is similar:
`Store (\_SB.PCI0.LPCB.EC.HWAC, Local0)` -> if you replace it is XWAC 
Also here XWAC isn't called as a method.

So maybe we should declare XWAC as an IntObj, what do you think?
`Name(XWAC, something)`

**Comment by benbender** [comment]
Does it throw an error in `log`?

(the "faulty" external-definition is generally not a problem)

**Comment by antoniomcr96** [comment]
> Does it throw an error in `log`?
```
2020-11-16 00:02:11.220359+0100 0x71       Default     0x0                  0      0    kernel: (AppleACPIPlatform) ACPI:
2020-11-16 00:02:11.220515+0100 0x71       Default     0x0                  0      0    kernel: (AppleACPIPlatform) SSDT 0x000000007ABFA000 0000C3 (v02 tyler  _HWAC    00001000 INTL 20200528)
2020-11-16 00:02:11.220516+0100 0x71       Default     0x0                  0      0    kernel: (AppleACPIPlatform) SSDT 0x000000007ABFA000 0000C3 (v02 tyler  _HWAC    00001000 INTL 20200528)
2020-11-16 00:02:11.222448+0100 0x71       Default     0x0                  0      0    kernel: (AppleACPIPlatform) 
```
Nono, it loads correctly. I think that, in general, whenever the system calls _L17 method nothing happens. In fact the system tries to assign to local 0 the value of: \_SB.PCI0.LPCB.H_EC.XWAC
`Local0 = \_SB.PCI0.LPCB.H_EC.XWAC`
But XWAC doesn't exist because it only exists as a method. It should happens the same for X1C6

**Comment by benbender** [comment]
As I said before, the technique is (probably) slightly out of spec but works. Afaik GPE-Events don't run inside the kernel and aren't logged therefor. It should be fine now. A better example where you can test the technique if you wish to is the battery handling - as those methods (_BIX/_BST/etc) are called on the EC by SMCBatteryManager from inside the kernel their output is properly logged and crashes are also visible in the logs... ;)

PS: As HWAC crashes on access because the darwin-kernel doesn't handle 16bit-reads it needs to be replaced even if its only read once and nothing is done with the result

**Comment by antoniomcr96** [comment]
Ok, thank you. I'm not an expert, my problem was about the syntax of the code that I thought it might not work. Thanks for the explanation about GPE-Events, now it makes a sense. I'll leave the patch as you made it, if it works for you it will work also for me. 

For now I think you can close this issue. In the next weeks I'll try to make SSDT-SLEEP working for my ACPI table. I think you did a great job in fitting native MacOS code.

Thanks for all the explanations and for your time. If I realize a repo I will put a reference for your work (and sorry for my bad English, I'm not a native speaker)

**Comment by benbender** [comment]
> Ok, thank you. I'm not an expert, my problem was about the syntax of the code that I thought it might not work. Thanks for the explanation about GPE-Events, now it makes a sense. I'll leave the patch as you made it, if it works for you it will work also for me.

Glad to help. And about being an expert: neither am I! Hackintoshing is a nice way to get an insight to some low-level-stuff you normally almost never get in touch with. And I for myself also having more questions than answers ;)

> For now I think you can close this issue. In the next weeks I'll try to make SSDT-SLEEP working for my ACPI table. I think you did a great job in fitting native MacOS code.

Cool! Especially if you publish your work/findings and others can learn and build upon it. Thats exactly why I'm publishing my progress here. Way to many hackintosh-setups are purely copy & paste (and boring...)!

> Thanks for all the explanations and for your time. If I realize a repo I will put a reference for your work (and sorry for my bad English, I'm not a native speaker)

Same for me... And give me a shout if you publish your repo!

**Comment by antoniomcr96** [comment]
Sorry @benbender , why did you remove your MAT0 device from ACPI tables (SSDT-DMAC if I don't remember wrong)? Thanks

**Comment by benbender** [comment]
Because it doesn't seem to have any impact/effect. Less code = less bugs ;)

**Comment by antoniomcr96** [comment]
Ok, I'll remove the _STA = 0xf that I previously set. I believe in what you think lol
If you can, let me eventually know if you find out if DMAC and PWB have any effect

**Comment by benbender** [comment]
- PWRB lets the system recognize the powerbutton and triggers the action according to the OS. F.e. lock the system on press on press in Big Sur.

- DMAC loads the driver for the  Direct Memory Access Controller. Its there in the original apple-ACPI.

**Comment by antoniomcr96** [comment]
1. The problem is that PWRB is never called in my ACPI. Have you made a custom SSDT that calls PWRB with some EC event? 

2. @benbender Look at this: https://github.com/VoodooI2C/VoodooI2C/issues/408#issuecomment-732370167. I think it could also interest you. On Lenovo laptops it seems to be a very good idea to disable unused I2C devices. 
EDIT: it seems that manually setting _STA to Zero works. I don't see useless I2C devices on my IOReg anymore. I think that this is a battery-friend idea. I set both I2C0 and I2C1 _STA to zero because they aren't linked to any device. I set I2C2 _STA to zero only in MacOS because in windows it is linked to a device that handles Usb power or something similar (not compatible with macOS)

```
    Scope (\_SB.PCI0.I2C0) {
        Method (_STA, 0, NotSerialized)  // _STA: Status
        {
            Return (Zero)
        }
    }

    Scope (\_SB.PCI0.I2C1) {
        Method (_STA, 0, NotSerialized)  // _STA: Status
        {
            Return (Zero)
        }
    }

    Scope (\_SB.PCI0.I2C2) {
        Method (_STA, 0, NotSerialized)  // _STA: Status 
        {
            If (OSDW ()) {
                Return (Zero)
            }
            Return (0x0F)
        }
    }
```

**Comment by benbender** [comment]
1. The existence of the device let the driver load. The device itself has no "real" function.

2. Without tinkering in the advanced menu, no I2c-devices are enabled in the first place on the X1C6. So no need to patch anything.
