### ISSUE TITLE
  BATX:BSTPresentRate: BAT0  constant 0 in v7

### ISSUE THREAD

**Issue by buyddy** [benbender/x1c6-hackintosh#7]
Finally figured out how to output debug. Comparing v7 and v6,   "BATX:BSTPresentRate: BAT0" is always 0 in v7 regardless wether BBIS and Quickpoll are disabled or not. All other values are normal. this is the reason why remain time won't calculate.

**Comment by benbender** [comment]
Fixed in Rev. 8

**Comment by buyddy** [comment]
working perfect now! Thanks for your hard work!
