### ISSUE TITLE
Replicating this for other TB3 motherboards?

### ISSUE THREAD

**Issue by radianttap** [benbender/x1c6-hackintosh#8]
Hey man, what you have here seems to be one of the most thorough implementation of TB3 for Hackintosh.

Can you tell which of all those SSDTs I will need in order to try and replicate this for my Hack, using ASRock Z490 ITX/TB3 motherboard with its Titan Ridge controller? I am using iMacPro1,1 SMBIOS, not sure if I can take your files as starting point. I already have the complete dump of iMacPro1,1 ACPI tables, I see that its SSDT-9 handles TB3 implementation. 

But it's hard to figure out what you took from MacBookPro's ACPI and then what you modified (apart from possibly renaming RP05) to make it work with X1.

**Comment by benbender** [comment]
Hey,

a best writeup of the (more complex) problem is here: https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix

A simpler approach to follow might be found here: http://hackindrom.zapto.org/

In general there are multiple ways to get TB in a somehow working state. From a working as a "simple" PCI2PCI-bridge till a (as far as possible) complete native approach. My approach tries to get it as native as possible (with the "drawback" of being the hardest and possibly most unstable one).

In general you need to have "my" whole SSDT-TB-*.dsl-setup + correct drom + the ICM of the TB-controller in the correct state. And even than it might be a flaky solution as those operational states are never intended in the firmware and TB in general is a complex standard with daisy-chaining and multiple, quite different operational states.

So feel free to experiment, but be aware that the whole setup is probably far from stable or fully understood.

**Comment by radianttap** [comment]
Thanks for the Hackingdrom link - they actually have my board in the list.
I'll start from there and see where I end up.

Your approach is interesting because it sounds like you got force-power to work without TbtPowerForce.efi. Was this due to ACPI changes alone or it requires specific BIOS settings (like GPIOPower ON) in order to work? My impression is the former which is why it's interesting to me since my BIOS does not have that option.

**Comment by benbender** [comment]
My approach should work natively on the X1C6. It resets ICM (integrated connection manager) while booting and forces it in an inactive state, handling connection management in ACPI like apple does. The Hackindom-approach leaves the connection management to the ICM and uses PCI2PCI-bridges. This approach is fine for simpler applications on desktops which don't need power management. For laptops its a bit crap as you loose PM and the TB-controller is quite power hungry...

For forcepwr - there are race-conditions between osx-pci-enumeration and the tb-controllers subdevices becoming visible. Therefor the efi-approach is great. If you are willing to take the risk of those race conditions, many firmwares have methods for forcepwr. See f.e.: https://github.com/tianocore/edk2-platforms/blob/master/Platform/Intel/KabylakeOpenBoardPkg/Features/Tbt/AcpiTables/Tbt.asl#L1228

**Comment by radianttap** [comment]
Great info, thank you. I'm off to read and experiment, will try not to bother you too much. :)

**Comment by benbender** [comment]
Wish you the best and close this issue!
